name: Build and Test go-codec
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    strategy:
      matrix:
        go: [ '1.11', '1.16', '1.18', '1.19', master ]
        arch: [ amd64 ]
        os: [ ubuntu-latest ]
        go-tag: [ '', 'safe', 'notfastpath', 'codecgen' ]
        include: 
          - go: '1.19'
            arch: '386'            
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: 'on'
      COVER_GO_VERSION: '1.19'
      GOARCH: ${{ matrix.arch }}
    name: go ${{ matrix.go }} on ${{ matrix.arch }} using go tags ${{ matrix.go-tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        shell: bash
        run: |
          cd codec
          go test "-tags=alltests ${{ matrix.go-tag }}" -run=Suite -coverprofile "coverage.${{ matrix.go }}.${{ matrix.arch }}.${{ matrix.go-tag }}.txt" github.com/ugorji/go/codec
      - uses: codecov/codecov-action@v3
        if: matrix.go == env.COVER_GO_VERSION
        with:
          directory: ./codec


# No need to go get, as github knows its working out of this folder
# Most of our code is now the same since go1.12. Only before that did we selectively compile files.
# Ok to jump around, and only test 1.11, and the last 2 production releases and master.
# Test i386 on last production release.

# coverage:
#   if: ${{ always() }}
#   needs: [ tests]
#   steps:
#     - uses: codecov/codecov-action@v3
#       directory: ./codec

# steps:
#   - uses: actions/checkout@v3
#     with:
#       fetch-depth: 0 # required for new-from-rev option in .golangci.yml
